import turtle

screen = turtle.Screen()
screen.bgcolor("white")

pen = turtle.Turtle()
pen.pensize(5)  # Set the pen size

def draw_J():
    pen.up()
    pen.setheading(180)
    pen.fd(200)
    pen.fd(100)
    pen.setheading(0)
    pen.down()
    pen.fd(80)
    pen.rt(90)
    pen.fd(160)
    pen.circle(-40,180)
    pen.fd(20)
    pen.up()
    pen.setheading(0)
    pen.fd(120)

def draw_I():
    pen.up()
    pen.fd(20)
    pen.setheading(90)
    pen.fd(140)
    pen.setheading(180)
    pen.down()
    pen.fd(30)
    pen.backward(90)
    pen.fd(45)
    pen.setheading(270)
    pen.fd(200)
    pen.setheading(180)
    pen.fd(45)
    pen.bk(90)
    pen.up()
    pen.bk(30)

def draw_T():
    pen.up()
    pen.bk(35)
    pen.setheading(90)
    pen.fd(200)
    pen.setheading(180)
    pen.fd(45)
    pen.down()
    pen.bk(90)
    pen.fd(45)
    pen.setheading(270)
    pen.fd(200)
    pen.up()
    pen.setheading(0)
    pen.up()
    pen.fd(60)

def draw_U():
    pen.setheading(90)
    pen.fd(200)
    pen.down()
    pen.bk(150)
    pen.down()
    pen.circle(60,-180)
    pen.undo()
    pen.setheading(270)
    pen.circle(60,-180)
    pen.undo()
    pen.circle(60,180)
    pen.fd(150)

def drawSmiley():
    pen.pensize(3)
    pen.color('orange')
    pen.setheading(90)
    pen.up()
    pen.setheading(0)
    pen.fd(50)
    pen.down()
    pen.circle(80)
    pen.up()
    pen.setheading(90)
    pen.fd(10)
    pen.fd(30)
    pen.fd(60)
    pen.setheading(180)
    pen.fd(30)
    pen.fd(10)
    pen.circle(5)
    pen.down()
    pen.circle(5)
    pen.up()
    pen.bk(60)
    pen.bk(20)
    pen.down()
    pen.circle(5)
    pen.setheading(270)
    pen.up()
    pen.fd(80)
    pen.undo()
    pen.fd(60)
    pen.circle(-100,40)
    pen.undo()
    pen.setheading(180)
    pen.down()
    pen.circle(-100,40)
    pen.undo()
    pen.setheading(210)
    pen.circle(-100,40)
    pen.undo()
    pen.circle(-80,50)


draw_J()
pen.color('blue')
draw_I()
pen.pensize(2)
pen.color('red')
draw_T()
pen.pensize(5)
pen.color("green")
draw_U()
drawSmiley()
pen.hideturtle()
screen.mainloop()
